version: '3'
services:
  jenkins:
    container_name: jenkins
    build: build
    ports:
      - "8081:8080"
    volumes:
      - $HOME/Projects/blue-ocean:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw
